---
id: 1181
title: dropbox ошибка при запуске
date: 2011-06-26T14:18:01+00:00
author: vanoc
layout: post
guid: http://vanoc.ru/?p=1181
permalink: /ubuntu/1181/
categories:
  - runix
  - ubuntu
tags:
  - dropbox
---
Когда dropbox издевается и при запуске выдает вот такое:

`dropbox start -i<br />
Starting Dropbox...Traceback (most recent call last):<br />
  File "/usr/bin/dropbox", line 250, in handle_ok<br />
    self.download = DownloadState()<br />
  File "/usr/bin/dropbox", line 157, in __init__<br />
    self.size = int(self.file.info()['content-length'])<br />
  File "/usr/lib/python2.6/rfc822.py", line 388, in __getitem__<br />
    return self.dict[name.lower()]<br />
KeyError: 'content-length'`

не расстраивайтесь, достаточно всего лишь установить libnotify-bin.